### ISSUE TITLE
Try the most simple case and fail

### ISSUE THREAD

**Issue by skyline9002** [vvenegasv/exportable#1]
Could not load file or assembly 'Infodinamica.Framework.Core, Version=3.2.0.29908, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

   at Infodinamica.Framework.Exportable.Tools.MetadataHelper.GetHeadersFormat(Type type)
   at Infodinamica.Framework.Exportable.Engines.Excel.ExcelExportEngine.CreateSheet(KeyValuePair`2 excelSheet)
   at Infodinamica.Framework.Exportable.Engines.Excel.ExcelExportEngine.Export()

**Comment by vvenegasv** [comment]
Hi, sorry I was very busy. When you publish a new release, visual studio  not add all dependencies in the build directory.

To fix this, you could copy manually the followings DLL to the output folder:

1.- Infodinamica.Framework.Core
2.- NPOI
3.- NPOI.OOXML
4.- NPOI.OpenXml4Net
5.- NPOI.OpenXmlFormats
6.- ICSharpCode.SharpZipLib

This libraries are in /package:
1.- Infodinamica.Framework.Core.3.2.0.29908
2.- NPOI.2.1.3.1
3.- SharpZipLib.0.86.0

Tell me if you need more help.

Have a nice day
