### ISSUE TITLE
Guide issue 

### ISSUE THREAD

**Issue by nesreeen** [vvenegasv/exportable#2]
Thank you for this nice library .
There is an issue with guide data type as it returns error "can't convert System.guide to string" 
to solve this issue we have to change ExcelExportEngine line 255  to use convert.ToString(propValue) instead of direct string casting (string)
var cellValue = Convert.ToString(propValue); (this will solve guide casting issue )
instead of 
var cellValue = (string)propValue; (this will return error with guide)

Regards,

**Comment by vvenegasv** [comment]
Thank you for your feed back. Would you like to create a pull request with this fix?

You could use [the develop branch](https://github.com/vvenegasv/exportable/tree/develop) to get the latest version and merge to it. Besides, you could get help from this [link](https://help.github.com/articles/creating-a-pull-request/)

Best Regards

**Comment by vvenegasv** [comment]
This bug was fixed on 1.3.7.18658 release. See this [link ](https://github.com/vvenegasv/exportable/releases/tag/1.3.7.18658)for more information
