### ISSUE TITLE
How to change header color

### ISSUE THREAD

**Issue by lp4869** [vvenegasv/exportable#6]
How I can change header color before export with “IExportEngine”

**Comment by vvenegasv** [comment]
Hi, in [this](https://github.com/vvenegasv/exportable/blob/master/src/Exportable.Test/Tools/DummyPersonWithHeaderAttribute.cs) unit test is an example on how change the header color. 

As you can see, to change the header color, you need to specify the ExportableExcelHeader attribute. With this attribute, you can set the font size, font family, font color, border color and background color.

Please, let me know if you have more questions.

Best Regards!
